// Code generated by protoc-gen-go.
// source: protos/addressbook.proto
// DO NOT EDIT!

/*
Package addressbook is a generated protocol buffer package.

It is generated from these files:
	protos/addressbook.proto

It has these top-level messages:
	Person
	Persons
	Id
	Empty
	Book
*/
package addressbook

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Person struct {
	Id           int32                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name         string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email        string                `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	PhoneNumbers []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phoneNumbers" json:"phoneNumbers,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhoneNumbers() []*Person_PhoneNumber {
	if m != nil {
		return m.PhoneNumbers
	}
	return nil
}

type Person_PhoneNumber struct {
	PhoneNumber string           `protobuf:"bytes,1,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
	PhoneType   Person_PhoneType `protobuf:"varint,2,opt,name=phoneType,enum=addressbook.Person_PhoneType" json:"phoneType,omitempty"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Person_PhoneNumber) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Person_PhoneNumber) GetPhoneType() Person_PhoneType {
	if m != nil {
		return m.PhoneType
	}
	return Person_MOBILE
}

type Persons struct {
	People []*Person `protobuf:"bytes,1,rep,name=people" json:"people,omitempty"`
}

func (m *Persons) Reset()                    { *m = Persons{} }
func (m *Persons) String() string            { return proto.CompactTextString(m) }
func (*Persons) ProtoMessage()               {}
func (*Persons) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Persons) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

type Id struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *Id) Reset()                    { *m = Id{} }
func (m *Id) String() string            { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()               {}
func (*Id) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Id) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// Our address book file is just one of these.
type Book struct {
	People []*Person `protobuf:"bytes,1,rep,name=people" json:"people,omitempty"`
}

func (m *Book) Reset()                    { *m = Book{} }
func (m *Book) String() string            { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()               {}
func (*Book) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Book) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "addressbook.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "addressbook.Person.PhoneNumber")
	proto.RegisterType((*Persons)(nil), "addressbook.Persons")
	proto.RegisterType((*Id)(nil), "addressbook.Id")
	proto.RegisterType((*Empty)(nil), "addressbook.Empty")
	proto.RegisterType((*Book)(nil), "addressbook.Book")
	proto.RegisterEnum("addressbook.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AddressBook service

type AddressBookClient interface {
	GetPersons(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Persons, error)
	GetAddressBook(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Book, error)
}

type addressBookClient struct {
	cc *grpc.ClientConn
}

func NewAddressBookClient(cc *grpc.ClientConn) AddressBookClient {
	return &addressBookClient{cc}
}

func (c *addressBookClient) GetPersons(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Persons, error) {
	out := new(Persons)
	err := grpc.Invoke(ctx, "/addressbook.AddressBook/GetPersons", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressBookClient) GetAddressBook(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := grpc.Invoke(ctx, "/addressbook.AddressBook/GetAddressBook", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AddressBook service

type AddressBookServer interface {
	GetPersons(context.Context, *Empty) (*Persons, error)
	GetAddressBook(context.Context, *Id) (*Book, error)
}

func RegisterAddressBookServer(s *grpc.Server, srv AddressBookServer) {
	s.RegisterService(&_AddressBook_serviceDesc, srv)
}

func _AddressBook_GetPersons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServer).GetPersons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/addressbook.AddressBook/GetPersons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServer).GetPersons(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressBook_GetAddressBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServer).GetAddressBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/addressbook.AddressBook/GetAddressBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServer).GetAddressBook(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddressBook_serviceDesc = grpc.ServiceDesc{
	ServiceName: "addressbook.AddressBook",
	HandlerType: (*AddressBookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPersons",
			Handler:    _AddressBook_GetPersons_Handler,
		},
		{
			MethodName: "GetAddressBook",
			Handler:    _AddressBook_GetAddressBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/addressbook.proto",
}

func init() { proto.RegisterFile("protos/addressbook.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0x41, 0x6f, 0x94, 0x40,
	0x14, 0xc7, 0x65, 0xca, 0x52, 0x79, 0x98, 0xed, 0x32, 0xdd, 0xa4, 0x88, 0x1a, 0xc9, 0x9c, 0x36,
	0x69, 0x02, 0x71, 0x9b, 0x78, 0xf1, 0x54, 0xcc, 0xa6, 0x6e, 0xb4, 0x82, 0xa4, 0x89, 0x67, 0x90,
	0xb1, 0x4b, 0x0a, 0xcc, 0x84, 0x99, 0x35, 0x69, 0x8c, 0x17, 0xbf, 0x82, 0xdf, 0xa0, 0x47, 0x2f,
	0x7e, 0x18, 0xbf, 0x82, 0x1f, 0xc4, 0x30, 0xb4, 0x76, 0x30, 0xf5, 0xe0, 0x6d, 0xde, 0xff, 0xfd,
	0xde, 0xff, 0xff, 0x20, 0x0f, 0x3c, 0xde, 0x31, 0xc9, 0x44, 0x94, 0x97, 0x65, 0x47, 0x85, 0x28,
	0x18, 0xbb, 0x08, 0x95, 0x84, 0x1d, 0x4d, 0xf2, 0x1f, 0x9f, 0x33, 0x76, 0x5e, 0xd3, 0x28, 0xe7,
	0x55, 0x94, 0xb7, 0x2d, 0x93, 0xb9, 0xac, 0x58, 0x2b, 0x06, 0x94, 0x5c, 0x21, 0xb0, 0x52, 0xda,
	0x09, 0xd6, 0xe2, 0x29, 0xa0, 0xaa, 0xf4, 0x8c, 0xc0, 0x58, 0x4c, 0x32, 0x54, 0x95, 0x18, 0x83,
	0xd9, 0xe6, 0x0d, 0xf5, 0x50, 0x60, 0x2c, 0xec, 0x4c, 0xbd, 0xf1, 0x1c, 0x26, 0xb4, 0xc9, 0xab,
	0xda, 0xdb, 0x51, 0xe2, 0x50, 0xe0, 0x97, 0xf0, 0x80, 0x6f, 0x58, 0x4b, 0xdf, 0x6e, 0x9b, 0x82,
	0x76, 0xc2, 0x33, 0x83, 0x9d, 0x85, 0xb3, 0x7c, 0x1a, 0xea, 0x9b, 0x0d, 0x21, 0x61, 0x7a, 0xcb,
	0x65, 0xa3, 0x21, 0xbf, 0x06, 0x47, 0x6b, 0xe2, 0x00, 0x1c, 0xad, 0xad, 0xd6, 0xb2, 0x33, 0x5d,
	0xc2, 0x2f, 0xc0, 0x56, 0xe5, 0xd9, 0x25, 0x1f, 0x96, 0x9c, 0x2e, 0x9f, 0xfc, 0x33, 0xb2, 0x87,
	0xb2, 0x5b, 0x9e, 0x1c, 0x82, 0xfd, 0x47, 0xc7, 0x00, 0xd6, 0x69, 0x12, 0xaf, 0xdf, 0xac, 0x66,
	0xf7, 0xf0, 0x7d, 0x30, 0x5f, 0x25, 0xa7, 0xab, 0x99, 0xd1, 0xbf, 0xde, 0x27, 0xd9, 0xeb, 0x19,
	0x22, 0xcf, 0x61, 0x77, 0xf0, 0x12, 0xf8, 0x10, 0x2c, 0x4e, 0x19, 0xaf, 0xa9, 0x67, 0xa8, 0x8f,
	0xdc, 0xbf, 0x23, 0x31, 0xbb, 0x46, 0xc8, 0x1c, 0xd0, 0xba, 0xfc, 0xfb, 0xbf, 0x92, 0x5d, 0x98,
	0xac, 0x1a, 0x2e, 0x2f, 0xc9, 0x11, 0x98, 0x31, 0x63, 0x17, 0xff, 0xe5, 0xb9, 0xfc, 0x61, 0x80,
	0x73, 0x3c, 0xb4, 0xd5, 0x70, 0x02, 0x70, 0x42, 0xe5, 0xcd, 0x7a, 0x78, 0x34, 0xaa, 0x62, 0xfc,
	0xf9, 0x1d, 0x76, 0x82, 0x1c, 0x7c, 0xfd, 0xf9, 0xeb, 0x1b, 0x72, 0xf1, 0x9e, 0x3a, 0x8c, 0x4f,
	0xcf, 0x22, 0x7e, 0x6d, 0x91, 0xc0, 0xf4, 0x84, 0x4a, 0x3d, 0x62, 0x6f, 0x64, 0xb0, 0x2e, 0x7d,
	0x77, 0x24, 0xf4, 0x0c, 0x79, 0xa8, 0xec, 0xf6, 0xb1, 0x7b, 0x63, 0xd7, 0xb7, 0xa2, 0xcf, 0x55,
	0xf9, 0x25, 0x7e, 0x07, 0x07, 0x92, 0x7e, 0xd8, 0x84, 0x72, 0x2b, 0x36, 0x79, 0xa7, 0x8f, 0xc6,
	0xae, 0x16, 0x93, 0xaa, 0x6b, 0x4e, 0x8d, 0x2b, 0x84, 0x8e, 0xe3, 0xef, 0xe8, 0xd1, 0xd9, 0x80,
	0x2b, 0xb9, 0xd8, 0x7e, 0x0c, 0x35, 0xb4, 0xb0, 0xd4, 0xf1, 0x1e, 0xfd, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0x6e, 0xfe, 0x3b, 0xee, 0x03, 0x03, 0x00, 0x00,
}
